'use strict';

/**
 * cldrGui: encapsulate GUI functions.
 * Use an IIFE pattern to create a namespace for the public functions,
 * and to hide everything else, minimizing global scope pollution.
 * Ideally this should be a module (in the sense of using import/export),
 * but not all Survey Tool JavaScript code is capable yet of being in modules
 * and running in strict mode.
 */
const cldrGui = (function() {

	const vhtml = "<div data-dojo-type=\"dijit/Dialog\" data-dojo-id=\"ariDialog\" title=\"CLDR Survey Tool\"\n"
            + "    data-dojo-props=\"onHide: function(){ariReload.style.display='';ariRetry.style.display='none';   if(disconnected) { unbust();}}\">\n"
            + "\n"
            + "    <div id='ariContent' class=\"dijitDialogPaneContentArea\">\n"
            + "        <div id='ariHelp'><a href='http://cldr.unicode.org/index/survey-tool#disconnected'>Help</a></div>\n"
            + "        <p id='ariMessage'>\n"
            + "            This page is still loading. \n"
            + "        </p> \n"
            + "        <p id='ariSubMessage'>\n"
            + "            Please wait for this page to load. \n"
            + "        </p>\n"
            + "        <div id=\"ariDetails\" data-dojo-type=\"dijit/TitlePane\" data-dojo-props=\"title: 'Details', open: false \">\n"
            + "        <p id='ariScroller'>\n"
            + "        </p>\n"
            + "        </div>\n"
            + "    </div>\n"
            + "\n"
            + "    <div class=\"dijitDialogPaneActionBar\">\n"
            + "        <button id='ariMain' style='display: none; margin-right: 2em;' data-dojo-type=\"dijit/form/Button\" type=\"button\" onClick=\"window.location = survURL;\">\n"
            + "            Back to Locales\n"
            + "        </button>\n"
            + "        <button id='ariRetryBtn'  data-dojo-type=\"dijit/form/Button\" type=\"button\" onClick=\"ariRetry()\">\n"
            + "            <b>Reload</b>\n"
            + "        </button>\n"
            + "    </div>\n"
            + "</div>\n"
            + "\n"
            + "<div class=\"navbar navbar-fixed-top\" role=\"navigation\">\n"
            + "      <div class=\"container-fluid\">\n"
            + "        <div class=\"collapse navbar-collapse\">\n"
            + "        <p class=\"nav navbar-text\">Survey Tool [TODO: VERSION; PHASE]\n"
            + "        </p>\n"
            + "          <ul class=\"nav navbar-nav\">\n"
            + "            <li class=\"pull-menu\">\n"
            + "                  <a href=\"#\"><span class=\"glyphicon glyphicon-cog\"></span> <b class=\"caret\"></b></a>\n"
            + "                  <ul id='manage-list' class=\"nav nav-pills nav-stacked\" style=\"display:none\">\n"
            + "                    <li>\n"
            + "                        <button type=\"button\" class=\"btn btn-default toggle-right\">Toggle Sidebar <span class=\"glyphicon glyphicon-align-right\"></span></button>\n"
            + "                    </li>\n"
            + "                  </ul>\n"
            + "                  \n"
            + "           </li>\n"
            + "            <li class=\"dropdown\" id='title-coverage' style='display:none'>\n"
            + "                      <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Coverage: <span id=\"coverage-info\"></span></a>\n"
            + "                      <ul class=\"dropdown-menu\">\n"
            + "                      </ul>\n"
            + "           </li>\n"
            + "            \n"
            + "            <li>\n"
            + "                <a href='TODO: GENERAL_HELP_URL' target='_blank'>TODO: GENERAL_HELP_NAME</a>\n"
            + "            </li>\n"
            + "          </ul>\n"
            + "          <p class=\"navbar-text navbar-right\">\n"
            + "              <span id=\"flag-info\"></span>\n"
            + "            <span class=\"v-status\">TODO: v-status</span>\n"
            + "\n"
            + "              TODO: QUERY_EMAIL; voteCountMenu\n"
            + "          </p>\n"
            + "\n"
            + "            <p class='navbar-text navbar-right'><a href='https://www.unicode.org/policies/privacy_policy.html'>This site uses cookies.</a>\n"
            + "            </p>\n"
            + "\n"
            + "            <p class='specialmessage navbar-text navbar-right'>TODO: sm.getSpecialHeaderText()\n"
            + "            </p>\n"
            + "        \n"
            + "        </div>\n"
            + "      </div>\n"
            + "</div>\n"
            + "<div id=\"left-sidebar\">\n"
            + "    <div id=\"content-sidebar\">\n"
            + "        <div id=\"locale-info\">\n"
            + "            <div class=\"input-group input-group-sm\">\n"
            + "                  <span class=\"input-group-addon  refresh-search\"><span class=\"glyphicon glyphicon-search\"></span></span>\n"
            + "                  <input type=\"text\" class=\"form-control local-search\" placeholder=\"Locale\">\n"
            + "            </div>\n"
            + "            <span id=\"locale-clear\" class=\"refresh-search\">x</span>\n"
            + "            \n"
            + "            <div class=\"input-group input-group-sm\" id=\"locale-check-group\">\n"
            + "                    <label class=\"checkbox-inline\">\n"
            + "                              <input type=\"checkbox\" id=\"show-read\"> Show read-only\n"
            + "                    </label>\n"
            + "                    <label class=\"checkbox-inline\">\n"
            + "                              <input type=\"checkbox\" id=\"show-locked\"> Show locked\n"
            + "                    </label>\n"
            + "            </div>\n"
            + "        </div>\n"
            + "        <div id=\"locale-list\">\n"
            + "            \n"
            + "        </div>\n"
            + "        <div id=\"locale-menu\">\n"
            + "        \n"
            + "        </div>\n"
            + "    </div>\n"
            + "    \n"
            + "    <div id=\"dragger\">\n"
            + "        <span class=\"glyphicon glyphicon-chevron-right\"></span>\n"
            + "        <div id=\"dragger-info\"></div>\n"
            + "    </div>\n"
            + "</div>\n"
            + "\n"
            + "<div class=\"container-fluid\" id=\"main-container\">\n"
            + " <div class=\"row menu-position\">\n"
            + "    <div class=\"col-md-12\">\n"
            + "        <div id='toptitle'>\n"
            + "        \n"
            + "                <div id=\"additional-top\">\n"
            + "                    TODO:WEB-INF/tmpl/stnotices.jspf\n"
            + "                </div>\n"
            + "                <!-- top info -->\n"
            + "      \n"
            + "         <div id='title-locale-container' class='menu-container' style=\"display:none\">\n"
            + "                <h1><a href='#locales///' id='title-locale'></a></h1>\n"
            + "                <span id='title-dcontent-container'><a href='http://cldr.unicode.org/translation/default-content' id='title-content'></a></span>\n"
            + "         </div>\n"
            + "         \n"
            + "         <div id='title-section-container' class='menu-container'>\n"
            + "             <h1 id=\"section-current\"></h1>\n"
            + "             <div style=\"display:none\" id='title-section' data-dojo-type=\"dijit/form/DropDownButton\">\n"
            + "                  <span>(section)</span>\n"
            + "                  <div id='menu-section' data-dojo-type=\"dijit/DropDownMenu\"></div>\n"
            + "             </div>\n"
            + "         </div> \n"
            + "        <div id='title-page-container' class='menu-container'>\n"
            + "        </div>\n"
            + "       <div class='row' id='nav-page'>\n"
            + "            <div class='col-md-9'>\n"
            + "                <p class='nav-button'>\n"
            + "                  <button type=\"button\" class=\"btn btn-primary btn-xs\" onclick='chgPage(-1)'><span class='glyphicon glyphicon-arrow-left'></span> Previous</button>\n"
            + "                  <button type=\"button\" class=\"btn btn-primary btn-xs\" onclick='chgPage(1)'>Next <span class='glyphicon glyphicon-arrow-right'></span></button>\n"
            + "                  <button type=\"button\" class=\"btn btn-default btn-xs toggle-right\">Toggle Sidebar <span class=\"glyphicon glyphicon-align-right\"></span></button>\n"
            + "                \n"
            + "                </p>\n"
            + "                    <div class=\"progress nav-progress\">\n"
            + "                          \n"
            + "                          <div id=\"progress-voted\" class=\"progress-bar progress-bar-info tip-log\" title='Votes' style=\"width: 0%\">\n"
            + "                          </div>\n"
            + "                          <div id=\"progress-abstain\" class=\"progress-bar progress-bar-warning tip-log\" title='Abstain' style=\"width: 0%\">\n"
            + "                          </div>\n"
            + "                    </div>\n"
            + "                    <div class='counter-infos'><a onclick='cldrStForum.reload();'>Forum:</a>\n"
            + "                        <span id='vForum'>...</span> ●\n"
            + "                        Votes: <span id='count-voted'></span>\n"
            + "                        - Abstain: <span id='count-abstain'></span>\n"
            + "                        - Total: <span id='count-total'></span>\n"
            + "                    </div>\n"
            + "            </div>\n"
            + "       </div>\n"
            + "    </div>\n"
            + "  </div>\n"
            + "    <div class=\"row\" id=\"main-row\" style=\"padding-top:147px;\">\n"
            + "        <div class=\"col-md-9\">\n"
            + "            <div data-dojo-type=\"dijit/layout/ContentPane\" id=\"MainContentPane\" data-dojo-props=\"splitter:true, region:'center'\" >\n"
            + "                <div id=\"LoadingMessageSection\">Please Wait<img src='loader.gif' alt='Please Wait'></div>\n"
            + "                <div id=\"DynamicDataSection\" ></div>\n"
            + "                <div id='nav-page-footer'>\n"
            + "                    <p class='nav-button'>\n"
            + "                        <button type=\"button\" class=\"btn btn-primary btn-xs\" onclick='chgPage(-1)'><span class='glyphicon glyphicon-arrow-left'></span> Previous</button>\n"
            + "                        <button type=\"button\" class=\"btn btn-primary btn-xs\" onclick='chgPage(1)'>Next <span class='glyphicon glyphicon-arrow-right'></span></button>\n"
            + "                        <button type=\"button\" class=\"btn btn-default btn-xs toggle-right\">Toggle Sidebar <span class=\"glyphicon glyphicon-align-right\"></span></button>\n"
            + "                    </p>\n"
            + "                </div>\n"
            + "                <div id=\"OtherSection\"></div>\n"
            + "            </div>\n"
            + "        </div>\n"
            + "        <div class=\"col-md-3\">\n"
            + "            <div id=\"itemInfo\" class=\"right-info\" data-dojo-type=\"dijit/layout/ContentPane\" data-dojo-props=\"splitter:true, region:'trailing'\" ></div>\n"
            + "        </div>\n"
            + "        \n"
            + "    </div>\n"
            + "    \n"
            + "    <div id=\"ressources\" style=\"display:none\">\n"
            + "    \n"
            + "    </div>\n"
            + "</div>\n"
            + "<div id=\"overlay\"></div>\n"
            + "<div class=\"modal fade\" id=\"post-modal\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n"
            + "  <div class=\"modal-dialog modal-lg\">\n"
            + "    <div class=\"modal-content\">\n"
            + "      <div class=\"modal-header\">\n"
            + "        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n"
            + "        <h4 class=\"modal-title\">Post</h4>\n"
            + "      </div>\n"
            + "      <div class=\"modal-body\">\n"
            + "      </div>\n"
            + "    </div>\n"
            + "  </div>\n"
            + "</div>\n";

	/**
	 * Set up the DOM and start executing Survey Tool as a single page app
	 */
	function run() {
		console.log("Hello my name is cldrGui.run");
		document.body.innerHTML = vhtml;
		showV(); // in CldrSurveyVettingLoader.js
	}

	/*
	 * Make only these functions accessible from other files:
	 */
	return {
		run: run,
	};
})();
